name: Policy Scan

on:
  workflow_call: {}

jobs:
  scan:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Check for secrets (Gitleaks)
        uses: zricethezav/gitleaks-action@v2
        with:
          config: gitleaks.toml
        continue-on-error: true

      - name: Check LICENSE file exists
        run: |
          if [ ! -f LICENSE ]; then
            echo "❌ LICENSE file is missing."
            exit 1
          fi

      - name: Check README file exists
        run: |
          if [ ! -f README.md ]; then
            echo "❌ README.md file is missing."
            exit 1
          fi

      - name: Scan for "do not commit" strings
        run: |
          if grep -rni 'do not commit' .; then
            echo "❌ Found 'do not commit' markers in code!"
            exit 1
          fi

      - name: (Optional) Run Trivy to check for known vulnerabilities
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: fs
          ignore-unfixed: true
          format: table
          exit-code: 1
        continue-on-error: true
