name: Policy Scan

on:
  workflow_call:
    inputs:
      check_license:
        required: false
        type: boolean
        default: true
      check_readme:
        required: false
        type: boolean
        default: true

jobs:
  scan:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run Gitleaks (v7, free)
        run: |
          curl -sSL https://github.com/zricethezav/gitleaks/releases/download/v7.6.1/gitleaks-linux-amd64 -o gitleaks
          chmod +x gitleaks
          ./gitleaks --path=. --verbose --report=gitleaks-report.json || true

      - name: Check for LICENSE file
        if: ${{ inputs.check_license }}
        run: |
          if [ ! -f LICENSE ]; then
            echo "❌ LICENSE file is missing."
            exit 1
          else
            echo "✅ LICENSE file found."
          fi

      - name: Check for README.md
        if: ${{ inputs.check_readme }}
        run: |
          if [ ! -f README.md ]; then
            echo "❌ README.md is missing."
            exit 1
          else
            echo "✅ README.md found."
          fi
          
      - name: Check if gitleaks-report.json was created
        run: |
          if [ -f gitleaks-report.json ]; then
            echo "✅ Gitleaks report generated."
          else
            echo "ℹ️ No gitleaks-report.json found. Likely no secrets detected."
          fi
    

      - name: Upload Gitleaks Report
        uses: actions/upload-artifact@v4
        with:
          name: gitleaks-report
          path: gitleaks-report.json
          if-no-files-found: ignore
